### ISSUE TITLE
Missing Psutil

### ISSUE THREAD

**Issue by MrSpaghatti** [NullArray/AutoSploit#1268]
Running an actual debian installation.
I cloned the master branch.
when running `sudo python autosploit.py` i get the error `No module named psutil` even tho i've already installed requirements.txt and can confirm that i have it installed.
I am running python 2.7
autosploit ver 4.0.
 - Python version number?
 - AutoSploit version number?
 - Any console output that is relevant to the issue:
 - Traceback (error) if any:

**Comment by CybertSys** [comment]
I get the same error. I'm running Python 3. 


Traceback (most recent call last):
  File "autosploit.py", line 1, in <module>
    from autosploit.main import main
  File "/home/kali/AutoSploit/autosploit/main.py", line 4, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by Ekultek** [comment]
try `python -m pip install psutil`
