### ISSUE TITLE
Can't seem to start autosploit -> Syntax error

### ISSUE THREAD

**Issue by GEXIMUZ** [NullArray/AutoSploit#1323]
I have installed AutoSploit on my kali machine but when I use the **$python autosploit.py** command I get the following error

Traceback (most recent call last):
  File "/home/kali/Desktop/AutoSploit/autosploit.py", line 1, in <module>
    from autosploit.main import main
  File "/home/kali/Desktop/AutoSploit/autosploit/main.py", line 135
    print error_traceback
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by saltasatelites** [comment]
I can't imagine why you want an abandoned tool if you don't know how to recognize whether it is written in Python2 or Python3. Please don't tell me ...

**Comment by runt1m3t3rr0r** [comment]
Try Running it as Root.

**Comment by saltasatelites** [comment]
I have no idea why I'm included in this issue, but this app hasn't been updated in 5 years and the error 'SyntaxError: Missing parentheses in call to 'print'. 'Did you mean print(...)?' It's because it uses an outdated version of python, probably python2.
