### ISSUE TITLE
autosploit wont run

### ISSUE THREAD

**Issue by LDD65** [NullArray/AutoSploit#146]
im trying to run on windows and i keep getting this error:

Traceback (most recent call last):
  File "autosploit.py", line 7, in <module>
    main()
  File "C:\Windows\System32\AutoSploit\autosploit\main.py", line 54, in main
    while not check_services(service):
  File "C:\Windows\System32\AutoSploit\lib\settings.py", line 98, in check_services
    all_processes.add(" ".join(running_proc.cmdline()).strip())
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 712, in cmdline
    return self._proc.cmdline()
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=104)

any fixes??

**Comment by Ekultek** [comment]
Are you using vagrant?

**Comment by LDD65** [comment]
no

**Comment by Ekultek** [comment]
autosploit was built to run on Linux, it has vagrant so you should try that out

**Comment by LDD65** [comment]
will do thanks

**Comment by Ekultek** [comment]
No problem, vagrant hasn’t been thought tested so if you do find some issues please report them
