### ISSUE TITLE
Services 

### ISSUE THREAD

**Issue by Ekultek** [NullArray/AutoSploit#91]
```
[←[1m←[32m+←[0m] checking for services
Traceback (most recent call last):
  File "autosploit.py", line 5, in <module>
    main()
  File "C:\Users\Nick\AutoSploit\autosploit\main.py", line 32, in main
    if not check_services(service):
  File "C:\Users\Nick\AutoSploit\lib\settings.py", line 94, in check_services
    all_processes.add(" ".join(running_proc.cmdline()).strip())
  File "C:\Python27\lib\site-packages\psutil\__init__.py", line 712, in cmdline
    return self._proc.cmdline()
  File "C:\Python27\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=312)
```

Privately reported

**Comment by Ekultek** [comment]
After looking into this more, it appears someone is trying to run AS on windows. So we're gonna close this
