### ISSUE TITLE
Error in python3 tryes to start in python2 shows this

### ISSUE THREAD

**Issue by festimii** [NullArray/AutoSploit#96]
- Python version number (2.7..)
 - AutoSploit version number (2.0)
 - Traceback (error) if any:

root@KALI:~/Desktop/AutoSploit-2.0# python autosploit.py
Traceback (most recent call last):
  File "autosploit.py", line 1, in <module>
    from autosploit.main import main
  File "/root/Desktop/AutoSploit-2.0/autosploit/main.py", line 3, in <module>
    from lib.cmdline.cmd import AutoSploitParser
  File "/root/Desktop/AutoSploit-2.0/lib/cmdline/cmd.py", line 9, in <module>
    import api_calls.censys
  File "/root/Desktop/AutoSploit-2.0/api_calls/censys.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable

**Comment by Ekultek** [comment]
Use python2 for now

**Comment by festimii** [comment]
yes but in python2 isn't working too in fact it shows the error i submitted it may be just a miss configure on my PC im not sure

**Comment by Ekultek** [comment]
Reinstall the requirements and install OpenSSL
