### ISSUE TITLE
It's a problem when I try to start autosploit.py

### ISSUE THREAD

**Issue by dAtiuy** [NullArray/AutoSploit#98]
Python
Problem nr1 with Python
This is the "error":
__________________________________

[+] welcome to autosploit, give us a little bit while we configure
[+] checking for services
Traceback (most recent call last):
  File "autosploit.py", line 5, in <module>
    main()
  File "/data/data/com.termux/files/home/AutoSploit/autosploit/main.py", line 33, in main
    choice = prompt("it appears that service {} is not enabled, would you like us to enable it for you[y/N]".format(service))
  File "/data/data/com.termux/files/home/AutoSploit/lib/output.py", line 10, in prompt
    question = raw_input(
NameError: name 'raw_input' is not defined
Python2 
The problem that I get when I try python2 autosploit.py
The "error":
python2 autosploit.py
Traceback (most recent call last):
  File "autosploit.py", line 1, in <module>
    from autosploit.main import main
  File "/data/data/com.termux/files/home/AutoSploit/autosploit/main.py", line 3, in <module>
    from lib.cmdline.cmd import AutoSploitParser
  File "/data/data/com.termux/files/home/AutoSploit/lib/cmdline/cmd.py", line 7, in <module>
    import lib.jsonize
  File "/data/data/com.termux/files/home/AutoSploit/lib/jsonize.py", line 7, in <module>
    import lib.settings
  File "/data/data/com.termux/files/home/AutoSploit/lib/settings.py", line 11, in <module>
    import psutil
ImportError: No module named psutil

**Comment by dAtiuy** [comment]
Btw I'm running the latest version of AutoSploit. I downloaded it from the here. Like 10 minutes ago.

**Comment by Ekultek** [comment]
`sudo pip2 install -r requirements.txt`

**Comment by dAtiuy** [comment]
Thanks.... I'm stupid.

**Comment by kiki-sasa** [comment]
Python
Problem nr1 with Python
This is the "error": DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
 more about python  support in pip

**Comment by FrankensteinEvil0069** [comment]
HEY I'M HAVING THIS NEW ERROR

 ./autosploit.py: line 1: from: command not found
./autosploit.py: line 2: from: command not found
./autosploit.py: line 8: syntax error near unexpected token `except'
./autosploit.py: line 8: `    except KeyboardInterrupt:'
 PLEASE HELP ME

**Comment by Git-AkshaySingh** [comment]
Hey i was trying to install Autospoit into ubuntu LTS and i am having problem. This is the link to the repo that i used @              
( https://github.com/NullArray/AutoSploit ).
I did as instructions said but i am getting the error : 
( python autosploit.py
Traceback (most recent call last):
  File "/home/snow/AutoSploit/autosploit.py", line 1, in <module>
    from autosploit.main import main
  File "/home/snow/AutoSploit/autosploit/main.py", line 135
    print() error_traceback
            ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
).

**Comment by gkrahman10-tech** [comment]
Traceback (most recent call):
 File "/root/Downloads/AutoSploit-3.0/autosploit/main.py", line 117, in main
    terminal.terminal_main_display(loaded_tokens)
  File "/root/Downloads/AutoSploit-3.0/lib/term/terminal.py", line 509, in terminal_main_display
    if "help" in choice_data_list:
TypeError: argument of type 'NoneType' is not iterable
